url:
baseurl: # /pairing-meetup

# Site settings
title: Fullstack LA
email:
description: "DTLA pair programming night MeetUp. We are a meet up in downtown
              LA focusing on pair programming. the meetup time consists of
              coding challenges found in katrina owens' exercism.io. we also
              use exercism.io to build community outside of the meetup."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Machiko Yasuda
  pic: 1
  position: orgainizer
  social:
    - title: twitter
      url: https://twitter.com/machikoyasuda
    - title: facebook
      url: #

- name: Kit Pearson
  pic: 2
  position: organizer
  social:
    - title: twitter
      url: https://twitter.com/kit_pearson
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/fullstackla
  - title: github
    url: http://github.com/fullstackla

# Postal address (add as many lines as necessary)
address:

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass

collections:
  events:
    output: true
