url:
baseurl: /pairing-meetup

# Site settings
title: DTLA Pair Programming
email:
description: "DTLA pair programming night MeetUp. We are a meet up in downtown
              LA focusing on pair programming. the meetup time consists of
              coding challenges found in katrina owens' exercism.io. we also
              use exercism.io to build community outside of the meetup."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Machiko Yasuda
  pic: 1
  position: co-orgainizer
  social:
    - title: twitter
      url: https://twitter.com/machikoyasuda
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Kit Pearson
  pic: 2
  position: co-organizer
  social:
    - title: twitter
      url: https://twitter.com/kit_pearson
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: #
  pic:
  position: #
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 362 E 2nd St,
  - line: Los Angeles, CA 90012

# Build settings
markdown: kramdown
permalink: pretty
